# Generated by Django 4.0.6 on 2023-07-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
