# Generated by Django 4.0.6 on 2023-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_like_user'),
        ('user', '0004_user_remove_sumyouser_user_ptr'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0004_alter_logentry_user'),
        ('refrigerator', '0002_alter_refrigerator_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumyoUser',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
