# Generated by Django 4.0.6 on 2023-08-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '이미지', 'verbose_name_plural': '이미지'},
        ),
        migrations.AlterModelTable(
            name='image',
            table='sumyo_image',
        ),
    ]
