# Generated by Django 4.0.6 on 2023-07-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': '재료',
                'verbose_name_plural': '재료',
                'db_table': 'sumyo_ingredient',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('detail', models.TextField()),
                ('image_route', models.TextField()),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'db_table': 'sumyo_recipe',
            },
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('method', models.CharField(max_length=20, null=True)),
                ('image_route', models.TextField(null=True)),
                ('ingredient', models.TextField(null=True)),
                ('cook_ingredient', models.ManyToManyField(to='cook.ingredient')),
                ('cook_recipe', models.ManyToManyField(to='cook.recipe')),
            ],
            options={
                'verbose_name': '요리',
                'verbose_name_plural': '요리',
                'db_table': 'sumyo_cook',
            },
        ),
    ]
