# Generated by Django 4.0.6 on 2023-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_recipe_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='image_route',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
