# Generated by Django 4.0.6 on 2023-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_cook_image_route_alter_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='ingredient',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='recipe',
            field=models.TextField(null=True),
        ),
    ]
