# Generated by Django 4.0.6 on 2023-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_alter_cook_ingredient_alter_cook_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='time',
        ),
    ]
