# Generated by Django 4.0.6 on 2023-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_remove_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_route',
            field=models.TextField(),
        ),
    ]
