# Generated by Django 4.0.6 on 2023-07-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_alter_recipe_image_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='recipe',
        ),
    ]
