name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: connect server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /root/sumyo_backend
          git pull origin main
          sudo systemctl restart gunicorn
          sudoy systemctl restart nginx
