# Generated by Django 4.0.6 on 2023-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerator',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
