# Generated by Django 4.0.6 on 2023-07-24 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refrigerator', '0002_alter_refrigerator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
